---
page-layout: full
title: "Resume"
toc: false
code-tools: false
number-sections: false
---
<!-- [Full Resume PDF](mysite-assets/resume.pdf) -->

## Education 

**The University of Chicago** (2024-2025) <br>
MS in Data Science (GPA: 3.93)

Relevant Coursework: Spectral Methods and Non-Convex Optimization, High Dimensional Time Series Analysis, Stochastic Processes, Machine Learning on Graphs, Groups, and Manifolds, Foundations of Machine Learning and AI I-II, Data Systems and Design.

**The University of Chicago** (2020-2024) <br>
BA in Mathematics, with honors (GPA: 3.78)

Relevant Coursework: Graduate Abstract Algebra I-II-III, Honors Analysis in Rn I-II-III, Optimization, Dynamical Systems, Differentiable Manifolds and Integration on Manifolds, Algebraic Topology, Algebraic Geometry, Complex Analysis, Mathematical Probability, Topics in Analysis (Geometric Measure Theory), Point-Set Topology, Quantum Mechanics I-II.

## Technical Skills

- Proficient in:
  - Python (Flask, Numpy, pandas, scikit-learn, PyTorch, JAX, matplotlib, transformers)
  - SQL 
  - Git (GitHub)
  - LaTeX

- Learning: 
  - Rust
  - C++
  - Typescript

## Experience 

- **University of Chicago Mathematics REU** (Summer 2024)<br>
**Apprentice Program Mentor** <br>
Mentored three undergraduate students and advised them in writing expository research papers.

- **University of Chicago Mathematics REU** (Summer 2023)<br>
**Full Program Participant** <br>
Worked with a graduate student mentor on writing an expository research paper at the intersection of algebraic topology
and algebraic geometry.<br>
Paper: Andre-Quillen (Co)Homology and the Cotangent Complex


- **University of Chicago Department of Mathematics** (Winter and Spring 2023)<br>
**Directed Reading Program** <br>
Worked with a graduate student mentor on an independent study of minimal surfaces and complex manifolds. 
Gave two public presentations on the relationship between minimal surfaces and complex analysis.

- **University of Chicago Department of Mathematics** (Autumn 2023)<br>
**Super Reader (Teaching Assistant)** <br>
Held a weekly office hour and graded all assignments for a section of Honors Calculus (IBL). 


- **University of Chicago Department of Astronomy and Astrophysics** (Summer and Autumn 2022)<br>
**Undergraduate Researcher** <br>
Worked with professor [Alex Ji](https://www.alexji.com/) on a research project investigating the kinematic properties of a tidally disrupting dwarf galaxy
orbiting the Milky Way. Independently conducted scientific data analysis in Python and used machine learning techniques to classify member
stars of the dwarf galaxy Antlia II. This research was funded by a grant from the Quad Undergraduate Research Scholars Program. <br>
See [research poster](https://ugradresearchsymposium.omeka.net/items/show/143).


- **University of Chicago Mathematics REU** (Summer 2021)<br>
**Apprentice Program Participant** <br>
Worked with a graduate student mentor to write an expository research paper on the asymptotic behavior of smooth
dynamical systems in the plane.<br>
Paper: Dynamical Systems in the Plane and the Poincare-Bendixson Theorem (cited by 1) 


## Grants and Awards
- University of Chicago Advanced Scholars Program (2024-2025)
- Dean's List (2022-2023)
- Quad Undergraduate Resarch Scholars Program (Summer 2022)
- Second place at the National APPE Intercollegiate Ethics Bowl (2022)


