---
execute:
  echo: true
  eval: true
  warning: true
  error: true 
title: "Monotone Light Factorizations"
author: "Noah Geller"
date: 04-01-2023
categories:
  - Math
  - Topology
---

We will show that any continuous map $f:X\to Y$ of compact Hausdorff spaces can be factored into a composition of two maps where one has connected fibers and the other has totally disconnected fibers. To start, we introduce some terminology and preliminary facts. 


**Definition**: Let $X$ be a topological space. A decomposition of $X$ is a partition of $X$ into compact subsets $\{C_\alpha\}$. The decomposition $\{C_\alpha\}$ is upper semi-continuous if whenever a decomposition element $C_\alpha$ is contained in an open set $U,$ there exists another open set $V\subset U$ which also contains $C_\alpha$ and has the property that for any other $C_\beta,$ if $C_\beta\cap V\neq \emptyset$ then $C_\beta\subset V.$

The condition to be a USC-decomposition looks a bit strange at first, but we shall see that it is exceedingly convenient and also not too difficult to satisfy in practice. 

For $X$ a topological space and $\mathcal{D} = \{C_\alpha\}$ an upper semi-continuous decomposition, we write $X/\mathcal{D}$ for the quotient space where each decomposition element $C_\alpha\in \mathcal{D}$ is collapsed to a point. As we will see, the condition that $\mathcal{D}$ is upper semi-continuous is equivalent to $X/\mathcal{D}$ being Hausdorff.

**Lemma**: Let $X$ be a topological space, $\{C_\alpha\}$ an upper semi-continuous decomposition, and $U\subset X$ an open set. Then, the union of all the decomposition elements contained in $U$ is an open set. 

*Proof*: Let $I = \{\alpha \mid C_\alpha\subset U\}$ and let $V = \bigcup_{\alpha\in I}C_\alpha.$ Let $x\in V$ be arbitrary. Then, there is some $C_\alpha$ such that $x\in C_\alpha\subset U.$ Because the decomposition $\{C_\alpha\}$ is USC, there exists an open set $U'\subset U$ such that $x\in C_\alpha\subset U'\subset U$ and if $C_\beta\cap U'\neq \emptyset$ then $C_\beta\subset U'.$ Let $y\in U'.$ Since $\{C_\alpha\}$ is a partition of $X$, there is a unique $C_\beta$ containing $y.$ In particular, this means that $C_\beta\cap U'$ is non-empty so $C_\beta\subset U'\subset U,$ i.e. $y\in V.$ Therefore, $U'\subset V$ is open and contains $x.$ Since $x\in V$ was arbitary, $V$ is an open set. 

Notice that the converse of this Lemma is also true by a very straightforward argument coming from the definition of upper semi-continuity. 

**Theorem**: Let $X$ be a compact Hausdorff space and let $\mathcal{D}=\{C_\alpha\}$ be an upper semi-continuous decomposition of $X$. Then, the quotient space $X/\mathcal{D}$ is also a compact Hausdorff space. 

*Proof*: The quotient space $X/\mathcal{D}$ is automatically compact since the quotient map $p:X\to X/\mathcal{D}$ is surjective and continuous. Let $C_\alpha,C_\beta\in X/\mathcal{D}.$ Because $X$ is Hausdorff and $C_\alpha,C_\beta\subset X$ are compact, they are also closed. Since $X$ is both compact and Hausdorff, it is also normal so there exists disjoint open sets $U_\alpha,V_\alpha \subset X$ such that $C_\alpha\subset U$ and $C_\beta\subset V.$ Let $V_\alpha$ be the union of all of the decomposition elements contained in $U_\alpha$ and let $V_\beta$ be the union of all the decomposition elements contained in $U_\beta.$ The sets $V_\alpha,V_\beta$ are both open by the above lemma. Moreover, $p(V_\alpha)$ and $p(V_\beta)$ are open in $X/\mathcal{D}$ (because of how $V_\alpha,V_\beta$ were constructed) and are disjoint. Thus, $X/\mathcal{D}$ is Hausdorff as desired. 

**Corollary 1**: For $X$ a compact Hausdorff space and $\mathcal{D} = \{C_\alpha\}$ a decomposition of $X$, $\mathcal{D}$ is USC if and only if $X/\mathcal{D}$ is Hausdorff. 

*Proof*: One direction is exactly the theorem we have just proven, so we just need to show that if $X/\mathcal{D}$ is Hausdorff, then $\mathcal{D}$ is USC. Suppose that $X/\mathcal{D}$ is Hausdorff. Since $X$ is compact Hausdorff and $X/\mathcal{D}$ is Hausdorff, the quotient map $p:X\to X/\mathcal{D}$ is a closed map. Let $U\subset X$ be open such that $U$ contains at least one decomposition element. Let $V$ be the union of all decomposition elements contained in the open set $U.$ Then, $p(V)$ is the complement of $p(X\setminus U)$ so $p(V)$ is open in $X/\mathcal{D}.$ Moreover, $V$ is a union of decomposition elements so $p^{-1}(p(V))=V$, i.e. $V$ is also open in $X$. Thus, $\mathcal{D}$ is USC. 

**Corollary 2**: Let $f:X\to Y$ be a surjective continuous map of compact Hausdorff spaces. Then, $\{f^{-1}(y)\mid y\in Y\}$ is a USC decomposition of $X$. 

*Proof*: Since $X,Y$ are compact Hausdorff, $f$ is a quotient map and every fiber is compact. Moreovoer, $Y$ being Hausdorff means we can apply Corollary 1 to get that $\{f^{-1}(y)\mid y\in Y\}$ is USC. 

Before tackling the main theorem, we need one more key lemma about USC decompositions which will do most of the work for us in proving the main theorem. 

**Key Lemma**: Let $X$ be a compact Hausdorff space and let $\mathcal{D}=\{C_\alpha\}$ be a USC decomposition of $X.$ Let $\mathcal{D}'$ be the decomposition whose elements are the connected components of the elements of $\mathcal{D}.$ Then, $\mathcal{D}'$ is also USC. 

*Proof*: Let $C_\alpha'\in \mathcal{D}'$ be a connected component of some $C_\alpha\in \mathcal{D}$ and suppose that $C_\alpha'\subset U$ for some open $U\subset X.$ Because $C_\alpha$ is compact and Hausdorff, there exists a set $D$ which is clopen in $C_\alpha$ such that $C_\alpha'\subset D\subset (U\cap C_\alpha).$ The set $D$ is open in $C_\alpha$ so there exists an open $U_D\subset X$ such that $D = U_D\cap C_\alpha.$ Moreover, $D$ is contained in $U$ so we can assume that $U_D\subset U$ (if not just intersect them). Because $D$ is clopen in $C_\alpha,$ $D = \overline{U_D}\cap C_\alpha$ as well. In particular, this means that $(\overline{U_D}\setminus U_D)\cap C_\alpha = \emptyset.$ Define $U^* = U_D\cup (X\setminus \overline{U_D})$ and note that $U^*$ is a disjoint union of two open sets and it contains $C_\alpha.$ Let $V$ be the union of all the elements in $\mathcal{D}$ which are contained in $U^*.$ Since $\mathcal{D}$ is USC, $V$ is open in $X$. Let $V'=V\cap U_D$ so $V'$ is open and contains $C_\alpha'.$ Suppose that $C_\beta'$ is a component of some $C_\beta\in \mathcal{D}$ such that $C_\beta$ intersects $V'$ non-trivially. By construction, $C_\beta$ must be contained within $V.$ Moreover, $C_\beta'$ is connected and intersects with $U_D$ so $C_\beta'$ must be contained in $U_D.$ Thus, $C_\beta'\subset V'\subset U_D\subset U.$ The open set $V'$ therefore demonstrates that $\mathcal{D}'$ is USC. 

**Definition**: A continuous map $f:X\to Y$ is monotone if all of its fibers are connected. 

**Definition**: A continuous map $f:X\to Y$ is light if all of its fibers are totally disconnected. 

We now have all of the ingredients we need to state and prove the Monotone-Light Factorization theorem: 

**Theorem (Monotone-Light Factorization)**: Let $f:X\to Y$ be a continuous mapping of compact Hausdorff spaces. Then, there exists a third compact Hausdorff space $Z$ and continuous maps $m:X\to Z$ and $l:Z\to Y$ such that $f = l\circ m$, $m$ is monotone, and $l$ is light. 

*Proof*: Let $\mathcal{D}$ be the decomposition of $X$ given by the connected components of the fibers of $f.$ Corollary 2 and our Key Lemma guarantee that this is a USC decomposition of $X$. Let $Z$ be the quotient space $X/\mathcal{D}$ and let $m:X\to Z$ be the quotient map. The space $Z$ is compact Hausdorff by our previous theorem and $m$ is monotone by construction. There is a natural map $l:Z\to Y$ which just takes a component of the fiber $f^{-1}(y)$ to the point $y.$ The map $l$ is light because the collection of components of a fiber $f^{-1}(y)$ will be totally disconnected in the quotient space $Z = X/\mathcal{D}.$

**References**:

Danny Calegari's Point Set-Topology Course at UChicago Winter 2023. 

Decompositions of Manifolds by Robert J. Daverman.
